import pandas as pd
df1 = pd.Series([1,2,8,4,6])
df2 = pd.Series([5,7,3,9,10])
print(df1)
print(df2)
print(f"Addition \n{df1 + df2}")
print(f"Subtraction \n{df1 - df2}")
print(f"Multiplication \n{df1 * df2}")
print(f"Division \n{df1 / df2}")
print(f"Module \n{df1 % df2}")
x = open("practice.txt", "a")
print(df1, file=x)
print(df2, file=x)
print(f"Addition \n{df1 + df2}", file=x)
print(f"Subtraction \n{df1 - df2}", file=x)
print(f"Multiplication \n{df1 * df2}", file=x)
print(f"Division \n{df1 / df2}", file=x)
print(f"Module \n{df1 % df2}", file=x)
x.close()
